### ISSUE TITLE
Compose module shows warning on Mac

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#1557]
Seems to be a peer dependency issue:

```
warning:
# github.com/fsnotify/fsevents
cgo-gcc-prolog:452:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
```

_Originally posted by @timotheus90 in https://github.com/testcontainers/testcontainers-go/issues/1337#issuecomment-1700631888_

**Comment by timotheus90** [comment]
"Seems to be a peer dependency issue on our side" is misleading here. Please remove that.^^ per dependency issue was fixed with `github.com/containerd/containerd v1.7.4 // indirect` in https://github.com/testcontainers/testcontainers-go/issues/1337#issuecomment-1700631888

**Comment by mmorel-35** [comment]
Is it fixed by #1617 ?

**Comment by mdelapenya** [comment]
I still see it on my Mac M1 🤔 

Need to go deeper into it but I'll prioritise the warning removal later on.

**Comment by paleboot** [comment]
Hola folks, one of our packages imports `modules/compose`, and we keep seeing the warning in our local machines.

It seems to stem from https://github.com/docker/compose.

<img width="466" alt="image" src="https://github.com/testcontainers/testcontainers-go/assets/54321501/863fe9e1-d72f-4078-b0b7-eca2d62dc08b">

- [pkg/compose/watch.go](https://github.com/docker/compose/blob/main/pkg/compose/watch.go#L33)
- [pkg/watch/watcher_darwin.go](https://github.com/docker/compose/blob/main/pkg/watch/watcher_darwin.go#L28)

A PR had been made in `fsevents` https://github.com/fsnotify/fsevents/pull/61 but it's still open.

**Comment by emanuel-skrenkovic** [comment]
Hello!

The `fsevents` issue that causes the warning (https://github.com/fsnotify/fsevents/issues/59) has been fixed and the fix is in `compose` version `2.27.1`. Switching to that version removes the warning.

**Comment by mdelapenya** [comment]
Given we are currently using compose v2.28.1, I think it's fine to close this. Thanks everybody involved 🙇
