### ISSUE TITLE
[Bug]: Could not start container: creating reaper failed

### ISSUE THREAD

**Issue by sebastianbuechler** [testcontainers/testcontainers-go#2477]
### Testcontainers version

0.30.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows 11

### Host arch

amd64

### Go version

1.21.6

### Docker version

```shell
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
$ docker info
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 44
  Running: 0
  Paused: 0
  Stopped: 44
 Images: 22
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 15.58GiB
 Name: docker-desktop
 ID: d6a66196-edce-47b4-86af-8679687c5b0c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### What happened?

I ran an integration test that spins up a PostgreSQL database which usually works without any issue on other systems. But on this machine it says:

```
2024/04/10 13:59:43 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 25.0.3
  API Version: 1.44
  Operating System: Docker Desktop
  Total Memory: 15951 MB
  Resolved Docker Host: tcp://127.0.0.1:50934
  Resolved Docker Socket Path: //./pipe/docker_engine
  Test SessionID: 5fa5f11f9fba7e7d7f5af0266e5babf8bc7030bec98b3d7607c4f7fd6ae973bb
  Test ProcessID: e97481d1-d819-42e3-bc0f-f07aad00f7a0
2024/04/10 13:59:43 Failed to get image auth for https://index.docker.io/v1/. Setting empty credentials for the image: testcontainers/ryuk:0.7.0. Error is:credentials not found in native keychain
2024/04/10 13:59:46 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/04/10 13:59:46 ✅ Container created: 9433fe236771
2024/04/10 13:59:46 🐳 Starting container: 9433fe236771
2024/04/10 13:59:46 ✅ Container started: 9433fe236771
2024/04/10 13:59:46 🚧 Waiting for container id 9433fe236771 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/04/10 13:59:47 failed accessing container logs: Error response from daemon: No such container: 9433fe2367714ff9aa681c31b776f9ceead5f282e8413c846641de31afd6e5ea
2024/04/10 13:59:47 Error response from daemon: No such container: 9433fe2367714ff9aa681c31b776f9ceead5f282e8413c846641de31afd6e5ea: could not start container: creating reaper failed: failed to create container
```

**Comment by dmakushin** [comment]
Same for me. Started after update to 0.30.0

**Comment by weeco** [comment]
V0.30.0 has been causing issues in my team as well. Different setups running Docker Desktop and Rancher - both running consistently into:

> port not found: creating reaper failed: failed to create container

or

> dial tcp [::1]:32810: connect: connection refused: Connecting to Ryuk on localhost:32810 failed: connecting to network reaper failed: failed to create network

Downgrading to v0.29.2 fixed it.

**Comment by mdelapenya** [comment]
Mmm I'm going to prioritise this, as it should work. From the logs, it seems Ryuk dies before the next container is started. Could you try [enabling the verbose mode in Ryuk](https://golang.testcontainers.org/features/configuration/#customizing-ryuk-the-resource-reaper) and trying to capture Ryuk logs and see if the connections are happening?

**Comment by miparnisari** [comment]
👋 seeing the same issue. https://github.com/openfga/openfga/actions/runs/8926586012/job/24517945125.

**Comment by stubents** [comment]
I'm not sure about the original error in this issue but the "port not found: creating reaper failed: failed to create container" that was mentioned by @weeco seems to be related to https://github.com/testcontainers/testcontainers-go/issues/605

With the commit 5fa65489 `DockerContainer.MappedPort(...)` now uses the ContainerJSON cache in `Inspect()` instead of always going for the client. And sometimes that cache happens to miss the mapping in the network settings.

In my setup this doesn't only affect Ryuk but other containers as well.
Commenting out the if condition at https://github.com/testcontainers/testcontainers-go/blob/5fa65489ac33e7a6a15e4599739b2c717cf3a1a9/docker.go#L168 solved the issue for me, but I'm not sure if this is a valid solution :)

**Comment by pr0ton11** [comment]
I encountered the same issue. Workaround of @stubents did not fix it for me.

**Comment by stubents** [comment]
> I encountered the same issue. Workaround of @stubents did not fix it for me.

Now, that I downgraded to `v0.29.1` I still see those "port not found" errors coming every now and then, so I guess 5fa6548 just made them more likely to happen.

**Comment by kiview** [comment]
I guess this should be fixed by https://github.com/testcontainers/testcontainers-go/pull/2508.

**Comment by pcriv** [comment]
@kiview I'm still having this issue with colima version 0.6.9, is there anything I can do to fix that?

**Comment by vec715** [comment]
any updates?

**Comment by stevenh** [comment]
Could be related to the fix here https://github.com/testcontainers/moby-ryuk/pull/121, still needs a release and then testcontainers-go updating to use the new image.

**Comment by strowk** [comment]
Just got this with version 0.32.0 on my Ubuntu machine. We get this once in awhile on CI as well (Github Actions), but I haven't seen this happening often on dev machine yet.

> panic: Error response from daemon: No such container: e4e95c74d1f499df597b3f93b8d3bb1df5bcfc11ca64cb63ac38c08607d50380: creating reaper failed: failed to create container [recovered]
        panic: Error response from daemon: No such container: e4e95c74d1f499df597b3f93b8d3bb1df5bcfc11ca64cb63ac38c08607d50380: creating reaper failed: failed to create container

Feels like, this should not be a closed issue, as it still happens on latest published version?

**Comment by mdelapenya** [comment]
@strowk does it happen using the HEAD commit in main?

We usually close the issues when PR fixing them are merged (thanks to Github links) so I think it's a common practice to do that.

**Comment by pixelsoccupied** [comment]
Hello! Trying out testcontainer for the first time and just into this issue. I see the bump Ryuk 0.8.1 but still getting this error

```
create container: started hook: wait until ready: dial tcp: lookup null: no such host: could not start container: creating reaper failed
```

My setup is super minimal. Just want to bring up a postgres container. 

```
pgContainer, err := postgres.Run(ctx,
		"postgres:16-alpine",
		postgres.WithDatabase("test-db"),
		postgres.WithUsername("postgres"),
		postgres.WithPassword("postgres"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).WithStartupTimeout(5*time.Second)),
	)
```

Using Colima + macOS. Curious if there's any workaround for this?

**Comment by pixelsoccupied** [comment]
Ah as a workaround I set env var `TESTCONTAINERS_RYUK_DISABLED` to `true`. It seems to get things going!

Related issue i think https://github.com/testcontainers/testcontainers-go/issues/2798 ?

**Comment by marcosfilhote** [comment]
Same problem here: 

```go
pgContainer, err := containerPostgres.Run(ctx,
		"docker.io/postgres:13.3-alpine",
		// containerPostgres.WithInitScripts(filepath.Join("../../assets", "db", "initdb.sql")),
		// containerPostgres.WithConfigFile(filepath.Join("testdata", "my-postgres.conf")),
		containerPostgres.WithDatabase(dbName),
		containerPostgres.WithUsername(dbUser),
		containerPostgres.WithPassword(dbPassword),
		// testcontainers.WithHostPortAccess(5432),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithStartupTimeout(25*time.Second),
			wait.ForListeningPort("5432/tcp"),
		),
	)
``` 

setting TESTCONTAINERS_RYUK_DISABLED to true to keep working.

**Comment by stevenh** [comment]
Could you check with the branch from https://github.com/testcontainers/testcontainers-go/pull/2728 to see if that fixes the issue for you?

**Comment by teenjuna** [comment]
Issue is still there as of v0.39.0. Setting `TESTCONTAINERS_RYUK_DISABLED=true` helps.

**Comment by thcdrt** [comment]
Same in v0.40

**Comment by mdelapenya** [comment]
@thcdrt could you please share the full test log and error? And, if possible, a code snippet with the error? As mentioned in https://github.com/testcontainers/testcontainers-go/issues/2477#issuecomment-2063036880, the project is widely used in the Go community, and this should have blocked them at some point.

For those disabling Ryuk, then the created containers won't be automatically pruned. I'd like to know if it's an environmental issue for Testcontainers in a given setup.

**Comment by XavierDuthil** [comment]
I'm responding on behalf of @thcdrt, here is an example test file that fails on our side with testcontainers v0.40.0:

```go
package tmptestcontainer

import (
	"context"
	"testing"
	"time"

	"github.com/docker/docker/api/types/container"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func NewDatabaseForTesting(ctx context.Context) (testcontainers.Container, error) {
	// _ = os.Setenv("TESTCONTAINERS_RYUK_DISABLED", "true")

	req := testcontainers.ContainerRequest{
		Image: "postgres:18.0-alpine3.22",
		Env: map[string]string{
			"POSTGRES_USER":     "postgres",
			"POSTGRES_PASSWORD": "postgres",
			"POSTGRES_DB":       "postgres",
		},
		WaitingFor:   wait.ForLog("database system is ready to accept connections").WithOccurrence(2).WithStartupTimeout(5 * time.Second), //nolint:gomnd,mnd
		ExposedPorts: []string{"5432"},
		HostConfigModifier: func(hostConfig *container.HostConfig) {
			// Not compatible with TESTCONTAINERS_RYUK_DISABLED=true environment variable. Terminate will give an error `Error response from daemon: removal of container d85edfa29717a32caf1f679a1453863510bddf93cad4f731d2f2a6f8308e8329 is already in progress`
			hostConfig.AutoRemove = true
		},
		Cmd: []string{"postgres", "-c", "fsync=off"},
	}

	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          false,
	})
	if err != nil {
		return nil, err
	}

	return container, nil
}

func TestTestcontainer(T *testing.T) {
	ctx := context.Background()

	database, err := NewDatabaseForTesting(ctx)
	if err != nil {
		T.Fatal(err)
	}

	err = database.Start(ctx)
	if err != nil {
		T.Fatal(err) // Fails when RYUK enabled: `create container: reaper: new reaper: run container: started hook: wait until ready: external check: check target: retries: 0 address: localhost:32804: unexpected container status "removing": could not start container`
	}

	err = database.Terminate(ctx)
	if err != nil {
		T.Fatal(err) // Fails when RYUK disabled & AutoRemove = true: `Error response from daemon: removal of container 9d4ce1956a4388cc112aa2d077a79e2b254728f2b1daab77cb1e492c8fe90bef is already in progress`
	}
}

```

The `database.Start()` fails with the following error:
```
    main_test.go:48: create container: reaper: new reaper: run container: started hook: wait until ready: internal check: unexpected container status "removing": could not start container
```

It works when I uncomment the `os.Setenv("TESTCONTAINERS_RYUK_DISABLED", "true")` & I disable `hostConfig.AutoRemove`.

Our docker version is v29.1.1 (company-managed).

Additional note: we were previously using the deprecated field `ContainerRequest.SkipReaper` which seemed to do the same as TESTCONTAINERS_RYUK_DISABLED=true but doesn't seem to work with latest versions.

**Comment by mdelapenya** [comment]
@XavierDuthil thanks for the code snippet. I executed it locally and here are my thoughts:

### 1. Container Start
I cannot reproduce the start error. I'm using Docker Desktop on a Mac M4. Could you share your docker info to understand which container runtime are you using?

This is the go.mod file:
```go
module github.com/mdelapenya/tmptestcontainers

go 1.25.4

require (
	github.com/docker/docker v28.5.1+incompatible
	github.com/testcontainers/testcontainers-go v0.40.0
)

require (
	dario.cat/mergo v1.0.2 // indirect
	github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1 // indirect
	github.com/Microsoft/go-winio v0.6.2 // indirect
	github.com/cenkalti/backoff/v4 v4.3.0 // indirect
	github.com/containerd/errdefs v1.0.0 // indirect
	github.com/containerd/errdefs/pkg v0.3.0 // indirect
	github.com/containerd/log v0.1.0 // indirect
	github.com/containerd/platforms v0.2.1 // indirect
	github.com/cpuguy83/dockercfg v0.3.2 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/distribution/reference v0.6.0 // indirect
	github.com/docker/go-connections v0.6.0 // indirect
	github.com/docker/go-units v0.5.0 // indirect
	github.com/ebitengine/purego v0.8.4 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/go-logr/logr v1.4.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/klauspost/compress v1.18.0 // indirect
	github.com/lufia/plan9stats v0.0.0-20211012122336-39d0f177ccd0 // indirect
	github.com/magiconair/properties v1.8.10 // indirect
	github.com/moby/docker-image-spec v1.3.1 // indirect
	github.com/moby/go-archive v0.1.0 // indirect
	github.com/moby/patternmatcher v0.6.0 // indirect
	github.com/moby/sys/sequential v0.6.0 // indirect
	github.com/moby/sys/user v0.4.0 // indirect
	github.com/moby/sys/userns v0.1.0 // indirect
	github.com/moby/term v0.5.0 // indirect
	github.com/morikuni/aec v1.0.0 // indirect
	github.com/opencontainers/go-digest v1.0.0 // indirect
	github.com/opencontainers/image-spec v1.1.1 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/power-devops/perfstat v0.0.0-20210106213030-5aafc221ea8c // indirect
	github.com/shirou/gopsutil/v4 v4.25.6 // indirect
	github.com/sirupsen/logrus v1.9.3 // indirect
	github.com/stretchr/testify v1.11.1 // indirect
	github.com/tklauser/go-sysconf v0.3.12 // indirect
	github.com/tklauser/numcpus v0.6.1 // indirect
	github.com/yusufpapurcu/wmi v1.2.4 // indirect
	go.opentelemetry.io/auto/sdk v1.1.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.49.0 // indirect
	go.opentelemetry.io/otel v1.38.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.38.0 // indirect
	go.opentelemetry.io/otel/metric v1.38.0 // indirect
	go.opentelemetry.io/otel/sdk v1.38.0 // indirect
	go.opentelemetry.io/otel/trace v1.38.0 // indirect
	go.opentelemetry.io/proto/otlp v1.9.0 // indirect
	golang.org/x/crypto v0.43.0 // indirect
	golang.org/x/sys v0.37.0 // indirect
	google.golang.org/protobuf v1.36.10 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

And this is the docker info from the test log:
```shell
=== RUN   TestTestcontainer
2025/12/01 12:20:00 github.com/testcontainers/testcontainers-go - Connected to docker:
  Server Version: 29.0.1
  API Version: 1.51
  Operating System: Docker Desktop
  Total Memory: 7837 MB
  Testcontainers for Go Version: v0.40.0
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: bb978d3cc3c1ab3f37bcdef85409ef677b74e930c2fb01cb7de0b36c3ad3d1d6
  Test ProcessID: 9f4e7be2-4abc-43d7-ab44-10eb3c1b53f1
```

### 2. Terminate error
We recommend using `testcontainers.Cleanup(t, ctr)` for terminating containers in tests, or use `testcontainers.TerminateContainer` in testable example: those test helpers handle nils properly.

We probably need to address that in the Terminate function, but the workaround would be to always use the helpers

**Comment by XavierDuthil** [comment]
@mdelapenya Thank you for taking the time to check this :)

I have a similar go.mod content, same docker version v28.5.1+incompatible.

Here are the verbose test logs containing the docker info:
```
=== RUN   TestTestcontainer
2025/12/01 14:30:23 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 29.1.1
  API Version: 1.51
  Operating System: Ubuntu 22.04.5 LTS
  Total Memory: 15260 MB
  Testcontainers for Go Version: v0.40.0
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: c7a88b564a74c03c5044fd1c065c9551c0293d014c2a04a0ab567669f85cb021
  Test ProcessID: 770d0662-c50b-4ac2-a11e-8aa7ba96207a
2025/12/01 14:30:23 🐳 Creating container for image postgres:18.0-alpine3.22
2025/12/01 14:30:23 🐳 Creating container for image testcontainers/ryuk:0.13.0
2025/12/01 14:30:23 ✅ Container created: 0e40d864a8f1
2025/12/01 14:30:23 🐳 Starting container: 0e40d864a8f1
2025/12/01 14:30:23 ✅ Container started: 0e40d864a8f1
2025/12/01 14:30:23 ⏳ Waiting for container id 0e40d864a8f1 image: testcontainers/ryuk:0.13.0. Waiting for: port 8080/tcp to be listening
2025/12/01 14:30:23 failed accessing container logs: Error response from daemon: can not get logs from container which is dead or marked for removal
2025/12/01 14:30:23 🐳 Stopping container: 0e40d864a8f1
2025/12/01 14:30:23 ✅ Container stopped: 0e40d864a8f1
2025/12/01 14:30:23 🐳 Terminating container: 0e40d864a8f1
2025/12/01 14:30:23 🚫 Container terminated: 0e40d864a8f1
    main_test.go:48: create container: reaper: new reaper: run container: started hook: wait until ready: internal check: unexpected container status "removing": could not start container
--- FAIL: TestTestcontainer (0.46s)
FAIL
FAIL	stash.ovh.net/raas/tmptestcontainer	0.525s
FAIL
```

And here is an extract of the `docker info` output from my terminal if it may be of use:
```
Client: Docker Engine - Community
 Version:    29.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.30.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.40.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
 [...]
 Server Version: 29.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Authorization: ovh
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c4457e00facac03ce1d75f7b6777a7a851e5c41
 runc version: v1.3.4-0-gd6d73eb8
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  userns
  cgroupns
 Kernel Version: 6.8.0-87-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 14.9GiB
 [...]
 Experimental: false
```

Thank you for the CleanupContainer tip, it seems to work fine! Will use this from now on

**Comment by mdelapenya** [comment]
@XavierDuthil do you have a testcontainers.properties in your $HOME? If so, could you paste its content? We recommend marking Ryuk as a privileged container (https://golang.testcontainers.org/features/configuration/#customizing-ryuk-the-resource-reaper), although we have internal discussions to remove that.

Could you check how Ryuk is created? Also, if you're able to capture Ryuk's logs, then we could identify why the container is not starting.

**Comment by XavierDuthil** [comment]
@mdelapenya No I don't have any such configuration file. Sadly we cannot use privileged containers as our docker configuration is locked by company policies (no root access).

Here I tried to run a Ryuk image directly (from DockerHub documentation https://hub.docker.com/r/testcontainers/ryuk):
```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock -e RYUK_PORT=8080 -p 8080:8080 docker.io/testcontainers/ryuk      
Unable to find image 'testcontainers/ryuk:latest' locally
latest: Pulling from testcontainers/ryuk
31603596830f: Pull complete 
c307511530fc: Pull complete 
6d9b4cc4a42f: Pull complete 
Digest: sha256:b2762871bff62df9bfcec62609da821803a575e06d74aa7ce1654ded208cc7c5
Status: Downloaded newer image for testcontainers/ryuk:latest
2025/12/01 16:21:58 Pinging Docker...
panic: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: dial unix /var/run/docker.sock: connect: permission denied

goroutine 1 [running]:
main.main()
	/go/src/github.com/testcontainers/moby-ryuk/main.go:36 +0x457
```

So I guess this would also be due to our restricted linux configuration policies, like /var/run/docker.sock not being mounted into containers so Ryuk can't access it?

**Comment by mdelapenya** [comment]
Tip: do not use `latest` with Ryuk, we intentionally do not update the latest tag to avoid mistakes.
```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock -e RYUK_PORT=8080 -p 8080:8080 docker.io/testcontainers/ryuk:0.14.0
```

I agree with you, it seems the issue comes with your restrictions, not with the library itself. In this case, I'd suggest disabling Ryuk and make it really consistent (even with a lint rule) to always call CleanupContainer *before* checking the Run error

**Comment by XavierDuthil** [comment]
Aright, needless to say I have the same with ryuk:0.14.0.

Indeed that explains everything, these policies do not allow us to use a container to manage other containers, so we need to clean them up in our tests teardown.

It was mainly the deprecated field ContainerRequest.SkipReaper which doesn't seem to work anymore in v0.40.0 (and for some time before that it seems) that drove us here. For anyone encountering the same issue, it should now be replaced by setting the env var TESTCONTAINERS_RYUK_DISABLED=true
